version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: importlib-metadata
    versions:
    - 3.10.0
    - 3.10.1
    - 3.4.0
    - 3.5.0
    - 3.7.0
    - 3.7.2
    - 3.7.3
    - 3.9.1
    - 4.0.0
  - dependency-name: asgiref
    versions:
    - 3.3.1
    - 3.3.2
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.1
    - 8.1.2
  - dependency-name: djangorestframework
    versions:
    - 3.12.2
  - dependency-name: zipp
    versions:
    - 3.4.0
  - dependency-name: django
    versions:
    - 3.0.7
